package com.itc.funkart.product_service.serviceImpl;

import com.itc.funkart.product_service.config.JwtConfig;
import com.itc.funkart.product_service.constants.JwtClaims;
import com.itc.funkart.product_service.service.JwtService;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import javax.crypto.SecretKey;
import java.util.Base64;

/**
 * <h2>JwtServiceImpl</h2>
 * <p>
 * Performs cryptographic validation of JSON Web Tokens.
 * This implementation relies on a shared HMAC secret key to ensure that
 * tokens were generated by the FunKart Auth Authority and have not been tampered with.
 * </p>
 */
@Service
@Slf4j
public class JwtServiceImpl implements JwtService {

    private final SecretKey key;

    /**
     * Constructs the service and decodes the Base64 secret.
     *
     * @param jwtConfig Configuration containing the raw Base64 secret.
     * @throws IllegalArgumentException if the secret is not valid Base64.
     */
    public JwtServiceImpl(JwtConfig jwtConfig) {
        try {
            byte[] keyBytes = Base64.getDecoder().decode(jwtConfig.getSecret());
            this.key = Keys.hmacShaKeyFor(keyBytes);
        } catch (IllegalArgumentException e) {
            log.error("CRITICAL: JWT Secret decoding failed. Check application properties.");
            throw e;
        }
    }

    /**
     * Parses and validates a JWT.
     * <p>
     * Validation steps:
     * 1. Signature check (Cryptographic integrity).
     * 2. Expiration check (Temporal validity).
     * 3. Issuer check (Identity provenance).
     * </p>
     *
     * @param token The JWT string to parse.
     * @return The payload of the token if all validations pass.
     * @throws io.jsonwebtoken.JwtException for any validation failure.
     */
    @Override
    public Claims parseJwtToken(String token) {
        return Jwts.parser()
                .verifyWith(key)
                .requireIssuer(JwtClaims.ISSUER)
                .build()
                .parseSignedClaims(token)
                .getPayload();
    }
}