pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins

  nodeSelector:
    eks.amazonaws.com/nodegroup: jenkins-node-group

  containers:
    - name: jnlp
      image: jenkins/inbound-agent:jdk17
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']

    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command: ["/busybox/sh"]
      args: ["-c", "sleep 999999"]
      tty: true

    - name: kubectl
      image: alpine/k8s:1.29.0
      command: ["cat"]
      tty: true

  restartPolicy: Never
'''
            defaultContainer 'jnlp'
        }
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                sh 'cd backend/catalogue-service && ./gradlew test --no-daemon'
            }
        }

        stage('Build JAR') {
            steps {
                sh 'cd backend/catalogue-service && ./gradlew build -x test --no-daemon'
            }
        }

        stage('Build & Push Image (Kaniko)') {
            steps {
                container('kaniko') {
                    sh '''
                    /kaniko/executor \
                      --dockerfile=backend/catalogue-service/Dockerfile \
                      --context=dir://backend/catalogue-service \
                      --destination=666127452756.dkr.ecr.eu-west-2.amazonaws.com/catalogue-service:latest \
                      --verbosity=info
                    '''
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                container('kubectl') {
                    sh '''
                    kubectl apply -f backend/catalogue-service/k8s/
                    kubectl get pods
                    '''
                }
            }
        }
    }
}