pipeline {
    agent any

    stages {

        stage('Test') {
            steps {
                sh 'cd backend/catalogue-service && ./gradlew test'
            }
        }

        stage('Build') {
            steps {
                sh 'cd backend/catalogue-service && ./gradlew build -x test'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'cd backend/catalogue-service && docker build -t catalogue-service .'
            }
        }

        stage('Docker Run') {
            steps {
                sh '''
                docker stop catalogue-service || true
                docker rm catalogue-service || true
                docker run -d -p 8081:8081 --name catalogue-service catalogue-service
                '''
            }
        }

    }
}

