spring:
  application:
    name: funkart

  config:
    import: optional:file:.env[.properties]

api:
  version: /api/v1

github:
  oauth:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: ${GITHUB_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${EXPIRATION_MS}
  cookie-max-age-seconds: ${JWT_COOKIE_MAX_AGE_SECONDS}

logging:
  level:
    org.springframework.core.env: INFO