spring:
  application:
    name: funkart
  web:
    resources:
      add-mappings: false

api:
  version: /api/v1

jwt:
  secret: ${JWT_SECRET:mXxbssTvw7+m8gAlzYhTCP4IyxMeOK2tDqSDPQAv6Qk=}
  expiration-ms: ${EXPIRATION_MS:3600000}
  cookie-max-age-seconds: ${JWT_COOKIE_MAX_AGE_SECONDS:3600}

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}

app:
  secure-cookie: ${APP_SECURE_COOKIE:false}

logging:
  level:
    org.springframework.core.env: INFO

github:
  oauth:
    client-id: ${GITHUB_CLIENT_ID}
    client-secret: ${GITHUB_CLIENT_SECRET}
    redirect-uri: ${GITHUB_REDIRECT_URI:http://localhost:8080/oauth/github/callback}