services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_INIT_LIMIT: 5
    networks:
      - db-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - db-network

  postgres:
    container_name: postgres-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    networks:
      - db-network

  user-service:
    container_name: user-service
    image: abbasgureitc/user-service:latest
    ports:
      - "8081:8080"
    networks:
      - db-network

  payment-service:
    container_name: payment-service
    image: abbasgureitc/payment-service:latest
    ports:
      - "8082:8080"
    networks:
      - db-network

  api-gateway:
    container_name: api-gateway
    image: abbasgureitc/api-gateway:latest
    ports:
      - "8080:8080"
    environment:
      USER_SERVICE_URL: http://user-service:8080
      PAYMENT_SERVICE_URL: http://payment-service:8080
      APP_API_VERSION: /api/v1
      APP_FRONTENDURL: http://localhost:5173
    networks:
      - db-network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080"
    networks:
      - db-network

  jenkins:
    user: root
    container_name: funkart-jenkins
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - gradle_cache:/root/.gradle
    networks:
      - db-network

volumes:
  jenkins_home:
  gradle_cache:

networks:
  db-network:
    driver: bridge