
spring:
  application:
    name: order-service

  datasource:
<<<<<<< HEAD
    url: jdbc:postgresql://18.132.197.27:32680/order-service
=======
    url: jdbc:postgresql://18.175.222.132:32680/order-service
>>>>>>> d0373b1 (fixed the db issue)
    username: postgres
    password: Ie422p9Cx8
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka.kafka.svc.cluster.local:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: service-events
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.itc.funkart.dto.OrderEvent

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8081

management:
  tracing:
<<<<<<< HEAD
    sampling:
      probability: 1.0
=======
    jaeger:
      enabled: true
      exporter:
        jaeger:
          endpoint: http://jaeger:14268/api/traces
      sampler:
        type: const
        param: 1.0
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
>>>>>>> d0373b1 (fixed the db issue)
