spring:
  application:
    name: order-service

  # --- Pagination Defaults ---
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        one-indexed-parameters: false # page=0 is the first page

  # --- Kafka Config ---
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: order-service-group-v1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.itc.funkart.dto"
        spring.json.value.default.type: com.itc.funkart.dto.OrderEvent

# Shared JWT settings
jwt:
  secret: ${JWT_SECRET:mXxbssTvw7Am8gAlzYhTCP4IyxMeOK2tDqSDPQAv6Qk0}
  expiration-ms: ${JWT_EXPIRATION:3600000}

server:
  port: 8080