spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:5432/order_prod
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASS}
    hikari:
      maximum-pool-size: 20

  kafka:
    bootstrap-servers: ${PROD_KAFKA_SERVER}
    producer:
      acks: all
      retries: 5
      properties:
        enable.idempotence: true
        compression.type: snappy

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.batch_size: 25

  data:
    redis:
      host: ${PROD_REDIS_HOST}
      ssl:
        enabled: true