spring:
  application:
    name: catalogue-service



server:
  port: 8081
  tomcat:
    threads:
      max: 400
    accept-count: 1500


resilience4j:
  ratelimiter:
    instances:
      productService:
        limitForPeriod: 1200
        limitRefreshPeriod: 1s
        #timeoutDuration: 0s

  timelimiter:
    instances:
      productService:
        timeoutDuration: 2s
        cancelRunningFuture: true

  retry:
    instances:
      productService:
        maxAttempts: 1
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 1
        retryExceptions:
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - io.github.resilience4j.ratelimiter.RequestNotPermitted

  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

management:
  endpoints:
    web:
      exposure:
        include: health,metrics