pipeline {
    agent any

    environment {
        DOCKER_USER     = 'ipenitcdocker'
        REPO_NAME       = 'product-service'
        IMAGE_NAME      = "${DOCKER_USER}/${REPO_NAME}"
        CREDS_ID        = 'DOCKER_HUB_CREDS'
        VERSION         = "1.0.${env.BUILD_NUMBER}"
        // The path to your project folder relative to the git root
        PROJECT_DIR     = 'backend/product-service'
    }

    stages {
        stage('Build Artifact') {
            steps {
                // Use 'dir' to change context to the project folder
                dir("${env.PROJECT_DIR}") {
                    sh "chmod +x gradlew"
                    sh "./gradlew clean build -x test"
                }
            }
        }

        stage('Build Image') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    // This finds the Dockerfile inside backend/product-service
                    sh "docker build -t ${IMAGE_NAME}:${VERSION} -t ${IMAGE_NAME}:latest ."
                }
            }
        }

        stage('Push to Hub') {
            steps {
                script {
                    docker.withRegistry('', "${env.CREDS_ID}") {
                        sh "docker push ${IMAGE_NAME}:${VERSION}"
                        sh "docker push ${IMAGE_NAME}:latest"
                    }
                }
            }
        }
    }

    post {
        always {
            sh "docker rmi ${IMAGE_NAME}:${VERSION} ${IMAGE_NAME}:latest || true"
        }
    }
}