/*
pipeline {
    agent any

    environment {
        AWS_REGION   = "eu-west-2"
        AWS_ACCOUNT_ID = "<your-aws-account-id>"
        ECR_REPO    = "review-rating-service"
        EKS_CLUSTER = "your-eks-cluster-name"
        AWS_CREDS   = credentials('aws-creds')
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/<your-user>/<your-repo>.git'
            }
        }

        stage('Build JAR') {
            steps {
                sh './gradlew clean bootJar'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    IMAGE_TAG = "${env.BUILD_NUMBER}"
                    sh """
                      docker build -t ${ECR_REPO}:${IMAGE_TAG} .
                    """
                }
            }
        }

        stage('Login to ECR') {
            steps {
                withEnv(["AWS_ACCESS_KEY_ID=${AWS_CREDS_USR}",
                         "AWS_SECRET_ACCESS_KEY=${AWS_CREDS_PSW}",
                         "AWS_DEFAULT_REGION=${AWS_REGION}"]) {
                    sh """
                      aws ecr get-login-password --region ${AWS_REGION} \
                      | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                    """
                }
            }
        }

        stage('Tag & Push Image') {
            steps {
                script {
                    sh """
                      docker tag ${ECR_REPO}:${IMAGE_TAG} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
                      docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
                    """
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                withEnv(["AWS_ACCESS_KEY_ID=${AWS_CREDS_USR}",
                         "AWS_SECRET_ACCESS_KEY=${AWS_CREDS_PSW}",
                         "AWS_DEFAULT_REGION=${AWS_REGION}"]) {

                    sh """
                      aws eks update-kubeconfig --region ${AWS_REGION} --name ${EKS_CLUSTER}

                      helm upgrade --install ${ECR_REPO} ./helm \
                        --set image.repository=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO} \
                        --set image.tag=${IMAGE_TAG}
                    """
                }
            }
        }
    }
} */
