spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reviews
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: your256bitsecretkeymustbeatleast32chars!!