package com.itc.funkart.repository;

import com.itc.funkart.common.enums.order.OrderStatus;
import com.itc.funkart.entity.Order;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

/**
 * <h2>Order Data Access Layer</h2>
 * <p>
 * Manages RDBMS operations for the Order Aggregate. Optimized for JVM performance
 * by utilizing Fetch Joins to prevent N+1 select issues.
 * </p>
 */
@Repository
public interface OrderRepository extends JpaRepository<Order, Long> {

    /**
     * Retrieves all orders for a customer with items eagerly loaded.
     * Uses 'distinct' to handle the Cartesian product generated by the join in the JVM.
     */
    @Query("SELECT DISTINCT o FROM Order o LEFT JOIN FETCH o.items WHERE o.customerId = :customerId ORDER BY o.createdAt DESC")
    List<Order> findByCustomerIdWithItems(@Param("customerId") Long customerId);

    /**
     * Secures order retrieval by verifying ownership and fetching items in one trip.
     */
    @Query("SELECT o FROM Order o LEFT JOIN FETCH o.items WHERE o.id = :id AND o.customerId = :customerId")
    Optional<Order> findByIdAndCustomerIdWithItems(@Param("id") Long id, @Param("customerId") Long customerId);

    /**
     * Paginated retrieval for administrative or status-based views.
     * Note: Avoid JOIN FETCH with Pagination in the same query, as Hibernate
     * will perform the join in the JVM Memory (Heap) rather than the DB.
     */
    Page<Order> findByStatus(OrderStatus status, Pageable pageable);
}