spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres-db:5432/mydb}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

# Stripe Credentials
stripe:
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  api-key: ${STRIPE_API_KEY}
  publishable-key: ${PUBLISHABLE_KEY_FOR_FRONTEND}