# ==============================================================
# PRODUCTION PROFILE
# ==============================================================
spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false