spring:
  config:
    activate:
      on-profile: dev
  datasource:
    # Uses DB_HOST if present, otherwise defaults to localhost
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/product_service_db
    username: product_user
    password: product_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    # Uses KAFKA_HOST if present, otherwise defaults to localhost
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
  data:
    redis:
      # Uses REDIS_HOST if present, otherwise defaults to localhost
      host: ${REDIS_HOST:localhost}
      port: 6379

  cache:
    redis:
      time-to-live: 3600000 # 10 minutes

management:
  otlp:
    tracing:
      # Uses OTLP_HOST if present, otherwise defaults to localhost
      endpoint: http://${OTLP_HOST:localhost}:4317/v1/traces