spring:
  application:
    name: product-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

jwt:
  secret: ${JWT_SECRET=mXxbssTvw7Am8gAlzYhTCP4IyxMeOK2tDqSDPQAv6Qk0}
  expiration: ${JWT_EXPIRATION:3600000}

management:
  otlp:
    tracing:
      endpoint: ${OTLP_ENDPOINT:http://localhost:4317}