spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://18.175.222.132:32680/postgres
    username: postgres
    password: Ie422p9Cx8
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    redis:
      time-to-live: 3600000
  kafka:
    bootstrap-servers: ae2c9c1e88ee:9092

management:
  otlp:
    tracing:
      endpoint: http://jaeger:4317/v1/traces
