apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-rating-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: review-rating-service
  template:
    metadata:
      labels:
        app: review-rating-service
    spec:
      containers:
        - name: review-rating-service
          image: <AWS_ID>.dkr.ecr.eu-west-2.amazonaws.com/review-rating-service:latest
          ports:
            - containerPort: 9097
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: reviews-db-secret
                  key: host
            - name: DB_PORT
              value: "5432"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reviews-db-secret
                  key: password
            - name: KAFKA_BOOTSTRAP
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: kafka-bootstrap
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: redis-host