# Catalogue Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue-service
  template:
    metadata:
      labels:
        app: catalogue-service
    spec:
      containers:
        - name: catalogue-service
          image: host.docker.internal:5000/catalogue-service-registry:local
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 7
            periodSeconds: 5

          env:
            - name: SPRING_REDIS_HOST
              value: "redis"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4318/v1/traces"


---
# Catalogue Service - (Service) - (exposes the app)
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  type: LoadBalancer
  selector:
    app: catalogue-service
  ports:
    - port: 8081
      targetPort: 8081