apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-worker
  namespace: catalogue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-worker
  template:
    metadata:
      labels:
        app: jmeter-worker
    spec:
      containers:
        - name: jmeter
          image: justb4/jmeter:latest
          command: ["/bin/sh"]
          args:
            - -c
            - |
              jmeter-server \
                -Dserver.rmi.ssl.disable=true \
                -Dserver.rmi.localport=50000 \
                -Dserver_port=1099
          ports:
            - containerPort: 1099
            - containerPort: 50000
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-worker
  namespace: catalogue-service
spec:
  selector:
    app: jmeter-worker
  ports:
    - name: rmi
      port: 1099
      targetPort: 1099
    - name: data
      port: 50000
      targetPort: 50000