apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-worker
  namespace: catalogue-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jmeter-worker
  template:
    metadata:
      labels:
        app: jmeter-worker
    spec:
      containers:
        - name: jmeter
          image: justb4/jmeter:latest
          command: ["jmeter-server"]
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-worker
  namespace: catalogue-service
spec:
  selector:
    app: jmeter-worker
  ports:
    - port: 1099