spring:
  application:
    name: api-gateway

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URL:http://user-service:8081}
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=2

            - id: payment-service
              uri: ${PAYMENT_SERVICE_URL:http://payment-service:8080}
              predicates:
                - Path=/api/v1/payments/**

            - id: product-service
              uri: ${PRODUCT_SERVICE_URL:http://product-service:8080}
              predicates:
                - Path=/api/v1/products/**

            - id: order-service
              uri: ${ORDER_SERVICE_URL:http://order-service:8080}
              predicates:
                - Path=/api/v1/orders/**


server:
  port: ${PORT:8060}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  services:
    user-service: ${USER_SERVICE_URL:http://user-service:8081}
    product-service: ${PRODUCT_SERVICE_URL:http://product-service:8082}
    order-service: ${ORDER_SERVICE_URL:http://order-service:8080}
    payment-service: ${PAYMENT_SERVICE_URL:http://payment-service:8080}
    catalogue-service: ${CATALOGUE_SERVICE_URL:http://catalogue-service:8080}
    notification-service: ${NOTIFICATION_SERVICE_URL:http://notification-service:8080}
    reviewrating-service: ${REVIEWRATING_SERVICE_URL:http://reviewrating-service:8080}

  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}
    cookie-max-age-seconds: ${JWT_COOKIE_MAX_AGE_SECONDS:3600}
    cookie-name: ${APP_COOKIE_NAME:token}
    secure-cookie: ${APP_SECURE_COOKIE:false}

  github:
    client-id: ${GITHUB_CLIENT_ID}
    client-secret: ${GITHUB_CLIENT_SECRET}
    redirect-uri: ${GITHUB_REDIRECT_URI:http://localhost:8060/oauth/github/callback}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,mappings
  endpoint:
    health:
      show-details: always