spring:
  application:
    name: funkart

  config: #importing env file properties
    import: optional:file:.env[.properties]

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

api:
  version: ${API_VERSION}