spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:create-drop}
    show-sql: ${SHOW_SQL:true}

logging:
  level:
    org.springframework.core.env: DEBUG

github:
  oauth:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: http://localhost:8080/oauth/github/callback

#old H2 quick in-memory datasource
#  datasource:
#    url: jdbc:postgresql://postgres:5432/mydb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password