spring:
  application:
    name: catalogue-service

server:
  port: 8081

resilience4j:
  timelimiter:
    instances:
      productService:
        timeoutDuration: 2s

management:
  endpoints:
    web:
      exposure:
        include: health,metrics