apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue-service
  template:
    metadata:
      labels:
        app: catalogue-service
    spec:
      nodeSelector:
        role: app
      containers:
        - name: catalogue-service
          image: 666127452756.dkr.ecr.eu-west-2.amazonaws.com/catalogue-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_REDIS_HOST
              value: "redis"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  type: LoadBalancer
  selector:
    app: catalogue-service
  ports:
    - port: 8081
      targetPort: 8081