apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: catalogue-service
spec:
  storageClassName: manual
  volumeName: redis-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi