pipeline {
    agent any

    tools {
        jdk 'jdk17'
    }

    environment {
        DOCKER_HUB_USER          = 'abbasgureitc'
        IMAGE_NAME               = 'user-service'
        REGISTRY_CREDENTIALS_ID  = 'docker-hub-credentials'
        SNYK_TOKEN               = credentials('snyk-token')
        dockerImage              = ''
    }

    stages {

        stage('Check Environment') {
            steps {
                sh 'java -version'
                sh 'docker version'
            }
        }


        stage('Build & Test') {
            steps {
                dir('backend/user-service') {
                    script {
                        sh "chmod +x gradlew"
                        sh "./gradlew clean build jacocoTestReport \
                                -Dspring.profiles.active=test \
                                --no-daemon --stacktrace"
                    }
                }
            }
        }

        stage('Security Scan (Snyk)') {
            options {
                timeout(time: 2, unit: 'MINUTES')
            }
            steps {
                dir('backend/user-service') {
                    script {
                        catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                            retry(3) {
                                sh 'snyk test --severity-threshold=high'
                            }
                            sh 'snyk monitor'
                        }
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                jacoco(
                    execPattern:      '**/build/jacoco/*.exec',
                    classPattern:     '**/build/classes/java/main',
                    sourcePattern:    '**/src/main/java',
                    inclusionPattern: '**/*.class',
                    minimumLineCoverage: '70',
                    maximumLineCoverage: '80',
                    buildOverBuild: true
                )
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend/user-service') {
                    script {
                        currentBuild.displayName = "#${env.BUILD_NUMBER} - ${IMAGE_NAME}"
                        dockerImage = docker.build(
                            "${DOCKER_HUB_USER}/${IMAGE_NAME}:${env.BUILD_NUMBER}", ".")
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('', REGISTRY_CREDENTIALS_ID) {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }
    }

    post {
        success { echo "SUCCESS: ${IMAGE_NAME} is live on Docker Hub." }
        failure { echo "FAILURE: Check Jacoco reports, test output, or Snyk logs." }
        always  { cleanWs() }
    }
}
