services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-server
    user: root

    ports:
      - "8082:8080"
      - "50000:50000"

    environment:
      - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP=

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERPROFILE}/.kube:/root/.kube

    extra_hosts:
      - "host.docker.internal:host-gateway"

    command: >
      bash -c "
      apt-get update &&
      apt-get install -y docker.io docker-compose &&
      exec /usr/local/bin/jenkins.sh
      "

volumes:
  jenkins_home:
    external: true